[package]
name = "hightly-socket-server"
version = "0.1.0"
authors = ["Semreg <vchabaniuk@yahoo.com>"]
edition = "2018"

[dependencies]
enigo = "0.0.13"
ws = "0.9.0"
env_logger = "0.6.2"
serde = "1.0.101"
serde_json = "1.0.40"
serde_derive = "1.0.101"
custom_derive = "0.1.7"
enum_derive = "0.1.7"